export default {
  type: "object",
  properties: {
    title: { type: "string" },
    amount: { type: "number" },
    jobType: { type: "string" },
    location: { type: "string" },
    description: { type: "string" },
    created: { type: "string", format: "date-time" },
    email: { type: "string" },
    userId: { type: "string", format: "mongoObjectId" },
    maxApplicants: { type: "number" },
    maxPositions: { type: "number" },
    activeApplications: { type: "number" },
    acceptedCandidates: { type: "string" },
    dateOfPosting: { type: "string", format: "date-time" },
    skillsets: { type: "string" },
    duration: { type: "number" },
    salary: { type: "number" },
    rating: { type: "number" },
  },
  required: [
    "title",
    "amount",
    "jobType",
    "location",
    "description",
    "email",
    "userId",
  ],
  additionalProperties: false,
};
